### ISSUE TITLE
use Django automatic primary-key generation?

### ISSUE THREAD

**Issue by pwalter2** [CoolNamesAllTaken/svb#20]
https://github.com/CoolNamesAllTaken/svb/blob/5da450e7ab281385d5f01ad0aed6927625346f36/code/svb-docker/python/svb_web/core/models.py#L12

See https://docs.djangoproject.com/en/4.2/topics/db/models/#automatic-primary-key-fields

I think we would prefer auto primary-key. Unique by default (no worries about collisions), and gives an int identifier that can be used in the admin as a last resort

**Comment by CoolNamesAllTaken** [comment]
I want us to have control over the primary key here since it will be printed on the card and we want it to be human readable. When I talked it through with Caitlin it sounds like we don't currently have any race conditions for customer creation. In the worst case, two people with the same name and costume initials have an account created for them in the exact same microsecond. Customer creation requests are processed one at a time due to the ACID properties of the database, so one account will get created first, and the second one will get created with its sequential identifier incremented by one. There's a hard limit of 9999 accounts / day but we shouldn't hit that.

If you can think of other issues with this approach, please let us know and we can fix it! DTV ran on custom primary keys for customer IDs and worked without issue last time, so I'm not too cocerned about this.

We will use automatic primary key generation for accounts, since those keys won't be visible to the end user.
